name: Build Jekyll

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Build and test with Jekyll
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
